parameters:
  core.entity.battle_field.class: CoreBundle\Entity\BattleField
  core.service.battle_field.class: CoreBundle\Service\BattleField\BattleFieldService
services:
  core.service.battle_field:
    class: '%core.service.battle_field.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.battle_field.class%'
      - '@event_dispatcher'
      - '@security.token_storage'
