parameters:
  core.handler.map_type.class: CoreBundle\Handler\MapTypeHandler
  core.entity.map_type.class: CoreBundle\Entity\MapType
  core.service.map_type.class: CoreBundle\Service\MapType\MapTypeService
services:
  core.handler.map_type:
    class: '%core.handler.map_type.class%'
    arguments:
      - '@service_container'
      - '@event_dispatcher'
      - '@core.service.map_type'
  core.service.map_type:
    class: '%core.service.map_type.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.map_type.class%'
      - '@event_dispatcher'
