imports:
  -
    resource: BattleServices.yml
  -
    resource: BattleStatusServices.yml
  -
    resource: BattleFieldStatusServices.yml
  -
    resource: CountShipsServices.yml
  -
    resource: MapServices.yml
  -
    resource: MapTypeServices.yml
  -
    resource: ShipServices.yml
  -
    resource: ShipLocationServices.yml
  -
    resource: ShipTypeServices.yml
  -
    resource: ShotServices.yml
  -
    resource: ShotStatusServices.yml
  -
    resource: UserServices.yml
  -
    resource: BattleFieldServices.yml
