parameters:
  core.entity.ship_type.class: CoreBundle\Entity\ShipType
  core.service.ship_type.class: CoreBundle\Service\ShipType\ShipTypeService
services:
  core.service.ship_type:
    class: '%core.service.ship_type.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.ship_type.class%'
      - '@event_dispatcher'
