parameters:
  core.entity.ship_location.class: CoreBundle\Entity\ShipLocation
  core.service.ship_location.class: CoreBundle\Service\ShipLocation\ShipLocationService
services:
  core.service.ship_location:
    class: '%core.service.ship_location.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.ship_location.class%'
      - '@event_dispatcher'
