parameters:
  core.handler.ship_location.class: CoreBundle\Handler\ShipLocationHandler
  core.entity.ship_location.class: CoreBundle\Entity\ShipLocation
  core.service.ship_location.class: CoreBundle\Service\ShipLocation\ShipLocationService
services:
  core.handler.ship_location:
    class: '%core.handler.ship_location.class%'
    arguments:
      - '@service_container'
      - '@event_dispatcher'
      - '@core.service.ship_location'
  core.service.ship_location:
    class: '%core.service.ship_location.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.ship_location.class%'
      - '@event_dispatcher'
