parameters:
  core.entity.shot_status.class: CoreBundle\Entity\ShotStatus
  core.service.shot_status.class: CoreBundle\Service\ShotStatus\ShotStatusService
services:
  core.service.shot_status:
    class: '%core.service.shot_status.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.shot_status.class%'
      - '@event_dispatcher'
