parameters:
  core.handler.shot_type.class: CoreBundle\Handler\ShotTypeHandler
  core.entity.shot_type.class: CoreBundle\Entity\ShotType
  core.service.shot_type.class: CoreBundle\Service\ShotType\ShotTypeService
services:
  core.handler.shot_type:
    class: '%core.handler.shot_type.class%'
    arguments:
      - '@service_container'
      - '@event_dispatcher'
      - '@core.service.shot_type'
  core.service.shot_type:
    class: '%core.service.shot_type.class%'
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@service_container'
      - '%core.entity.shot_type.class%'
      - '@event_dispatcher'
