security:

    providers:
        webservice:
            id: core.webservice_user_provider

    firewalls:
        dev:
            pattern: ^(/doc|/_wdt)
            security: false

        main:
            pattern:    ^/
            guard:
                authenticators:
                    - core.token_authenticator

#    access_control:
#        # require ROLE_ADMIN for /admin*
#        - { path: ^/battles, roles: ROLE_ADMIN }