security:

    encoders:
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        webservice:
            id: core.webservice_user_provider

    firewalls:
        dev:
            pattern: ^/_wdt
            security: false

        api_doc:
            pattern: ^/doc
            security: false

        register:
            pattern: ^/register
            security: false

        login:
            pattern: ^/login
            stateless: true
            guard:
                authenticators:
                    - core.password_authenticator

        main:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                    - core.token_authenticator

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_EDITOR]
#
#    access_control:
#        - { path: ^/battle/open, roles: ROLE_ADMIN }