security:
    encoders:
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        webservice:
            id: user_bundle.webservice_user_provider

    firewalls:
        dev:
            pattern: ^/_wdt
            security: false

        api_doc:
            pattern: ^/doc
            security: false

        register:
            pattern: ^/register
            security: false

        login:
            pattern: ^/login
            stateless: true
            guard:
                authenticators:
                    - user_bundle.password_authenticator

        main:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                    - user_bundle.token_authenticator