api_battle:
  resource: '@ApiBundle/Controller/BattleController.php'
  type: rest
  prefix: /
  defaults:
    _format: json
api_ship:
  resource: '@ApiBundle/Controller/ShipController.php'
  type: rest
  prefix: /
  defaults:
    _format: json
api_shot:
  resource: '@ApiBundle/Controller/ShotController.php'
  type: rest
  prefix: /
  defaults:
    _format: json
api_user:
  resource: '@ApiBundle/Controller/UserController.php'
  type: rest
  prefix: /
  defaults:
    _format: json
api_count_ships:
  resource: '@ApiBundle/Controller/CountShipsController.php'
  type: rest
  prefix: /
  defaults:
    _format: json
